export default [
    "Watermelon is 90% water, so it is a good refresher in the heat.",
    "Lemon contains more sugar than strawberries, but due to the acid it seems sour.",
    "Kiwi has more vitamin C than an orange.",
    "Cherries help to recover faster after physical activity.",
    "Plum can act as a natural digestive regulator.",
    "Mandarin is easy to peel due to its loose skin.",
    "Watermelon seeds can be eaten - they contain healthy fats.",
    "Lemon peel is often used in cooking because of its aroma.",
    "Kiwi was previously called “Chinese gooseberry”.",
    "Cherries can be both sweet and sour - these are different types.",
    "Plum has dozens of varieties with different colors - from yellow to dark purple.",
    "Watermelons can grow to very large sizes - over 10 kg.",
    "Mandarins are part of the citrus group along with lemons and oranges.",
    "Lemon has been used as a natural preservative since ancient times.",
    "Kiwi contains an enzyme that breaks down proteins.",
    "Cherry trees can live for decades.",
    "Plums are good for drying, which is how prunes are made.",
    "Watermelon is considered both a fruit and a berry from a botanical point of view.",
    "Tangerines are often associated with winter due to their seasonality.",
    "Lemon juice can slightly change the taste of other foods, enhancing them.",
    "Watermelon can retain moisture for a long time even after cutting.",
    "Kiwi has a thin but edible skin.",
    "Cherries are often used in desserts.",
    "Lemon goes well with water as a refreshing drink.",
    "Plums have a natural sweetness without added sugar.",
    "Tangerines are convenient to take with you because of their compact size.",
    "Watermelon is often eaten chilled.",
    "Kiwi has a bright green color due to chlorophyll.",
    "Cherry juice has a rich dark color.",
    "Lemon is used in drinks all over the world.",
    "Plums have smooth or slightly matte skin.",
    "Mandarins have a characteristic citrus aroma.",
    "Watermelon has black or light seeds.",
    "Kiwi is often added to fruit salads.",
    "Cherries have a stone inside.",
    "Lemons have a bright yellow color, which is easy to recognize.",
    "Plums can be both juicy and more dense.",
    "Tangerines can have different numbers of segments.",
    "Watermelon has a crunchy texture.",
    "Kiwi has a contrast between green flesh and dark seeds."
]